name: Download and Run Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create Scripts Directory
        run: |
          mkdir -p scripts

      - name: Download Hello World Script
        run: |
          cd scripts
          curl -O https://raw.githubusercontent.com/jessica-jorgenson/CSCI117/master/HelloWorld.py

      - name: Run Hello World Script
        run: |
          cd scripts
          python HelloWorld.py