name: Download and Run Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      
      - name: Download Hello World Script
        run: |
          curl -O https://raw.githubusercontent.com/aliphys/pythonicWorkflows/blob/main/scripts/hello_world.py

      - name: Run Hello World Script
        run: python hello_world.py
